PCS update
JuliaSmoothOptimizers/PartitionedStructures.jl pull request #47
Opened 2022-07-20 18:58 UTC by paraynaud

- add `convex::Bool` field to elemental element matrix 
- PCS update that update with BFGS if  `convex`with SR1 otherwise
- adapt usual elemental element and partitioned matrix definitions
- tests

2022-07-20 21:11 UTC, paraynaud commented
@dpo this PR:
- add a `convex` field to element matrices ;
- adapt partitioned matrices to it;
- define a partitioned update that update dense element matrix either with BFGS or SR1 depending to `convex` field.

I integrated these changes to PartiallySeparableNLPModels.jl and PartiallySeparableSolvers.jl.
PartiallySeparableNLPModels.jl integrate the convexity detection to the partitioned matrix defined with the argument option `name=:psc`.
They will need the version 0.1.1 implementing the changes of this PR.

2022-07-21 16:46 UTC, dpo requested changes
Looks great, thanks. Just some minor points.

2022-07-21 16:46 UTC, dpo commented on src/P_mat/elemental_pm.jl
> +  # eem_set = map((elt_var -> create_id_eem(elt_var; T = T)), element_variables)
remove dead code

2022-07-21 16:46 UTC, dpo commented on src/P_mat/elemental_em.jl
> +* `Bie`: the elemental matrix`::Symmetric{T, Matrix{T}}`;
```suggestion
* `Bie::Symmetric{T, Matrix{T}}`: the elemental matrix;
```
I find it clearer if you indicate types this way.

2022-07-21 19:18 UTC, dpo approved these changes

2022-07-21 20:36 UTC, paraynaud commented
Do I change the version number in this pull request to register it when we merge? or I make a new PR for that?

2022-07-21 21:35 UTC, dpo commented
Please open a new PR for that.

2022-07-21 21:35 UTC, merged

2022-07-21 21:35 UTC, dpo commented
Thanks!